language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel

  
  - docker tag udagram-api-feed shayhun/udagram-api-feed:v1
  - docker tag udagram-api-user shayhun/udagram-api-user:v2
  - docker tag udagram-frontend:local shayhun/udagram-frontend:v3
  - docker tag reverseproxy shayhun/reverseproxy:v4


after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push shayhun/udagram-api-feed:v1
  - docker push shayhun/udagram-api-user:v2
  - docker push shayhun/udagram-frontend:v3
  - docker push shayhun/reverseproxy:v4
